// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnnnxSjyyz10D6wX-0rFggQNZyz2NHi4k',
    appId: '1:950455124364:web:7d1d7ee8381c37b3ca96a9',
    messagingSenderId: '950455124364',
    projectId: 'crud-operation-1657a',
    authDomain: 'crud-operation-1657a.firebaseapp.com',
    storageBucket: 'crud-operation-1657a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO-wVdk3OYQGZ70lVfW_nXm3qjEbDfmq4',
    appId: '1:950455124364:android:f3717b8530460d52ca96a9',
    messagingSenderId: '950455124364',
    projectId: 'crud-operation-1657a',
    storageBucket: 'crud-operation-1657a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-1rNwOozq_r-hrEaSRyU0TWom9UIuSOg',
    appId: '1:950455124364:ios:79236635cd828846ca96a9',
    messagingSenderId: '950455124364',
    projectId: 'crud-operation-1657a',
    storageBucket: 'crud-operation-1657a.appspot.com',
    iosBundleId: 'com.example.crudOperationFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-1rNwOozq_r-hrEaSRyU0TWom9UIuSOg',
    appId: '1:950455124364:ios:79236635cd828846ca96a9',
    messagingSenderId: '950455124364',
    projectId: 'crud-operation-1657a',
    storageBucket: 'crud-operation-1657a.appspot.com',
    iosBundleId: 'com.example.crudOperationFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnnnxSjyyz10D6wX-0rFggQNZyz2NHi4k',
    appId: '1:950455124364:web:c1eb9b81245bc25dca96a9',
    messagingSenderId: '950455124364',
    projectId: 'crud-operation-1657a',
    authDomain: 'crud-operation-1657a.firebaseapp.com',
    storageBucket: 'crud-operation-1657a.appspot.com',
  );
}
